In [1]:
import pandas as pd

df1=pd.read_excel('Initial Data\Central Ludhiana_Revised.xlsx',index_col=0,sheet_name=2, usecols="A:H,O:Q,X:AG",skiprows=1)
df1.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df1['Barseem'] = df1['Barseem'].astype(str).str.replace("1","Barseem")
df1['Barseem'] = df1['Barseem'].astype(str).str.replace("0","")
df1['Bajra'] = df1['Bajra'].astype(str).str.replace("1","Bajra")
df1['Bajra'] = df1['Bajra'].astype(str).str.replace("0","")
df1['maize'] = df1['maize'].astype(str).str.replace("1","maize")
df1['maize'] = df1['maize'].astype(str).str.replace("0","")
df1['chari'] = df1['chari'].astype(str).str.replace("1","chari")
df1['chari'] = df1['chari'].astype(str).str.replace("0","")
df1['jawar'] = df1['jawar'].astype(str).str.replace("1","jawar")
df1['jawar'] = df1['jawar'].astype(str).str.replace("0","")

df1['Wheat Straw'] = df1['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df1['Wheat Straw'] = df1['Wheat Straw'].astype(str).str.replace("0","")
df1['Paddy Straw'] = df1['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df1['Paddy Straw'] = df1['Paddy Straw'].astype(str).str.replace("0","")

df1.fillna(method='ffill', inplace=True)

df2=pd.read_excel('Initial Data\Central Sangrur_Revised.xlsx',index_col=0,sheet_name=2, usecols="A:H,O:Q,X:AG",skiprows=1)
df2.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df2['Barseem'] = df2['Barseem'].astype(str).str.replace("1","Barseem")
df2['Barseem'] = df2['Barseem'].astype(str).str.replace("0","")
df2['Bajra'] = df2['Bajra'].astype(str).str.replace("1","Bajra")
df2['Bajra'] = df2['Bajra'].astype(str).str.replace("0","")
df2['maize'] = df2['maize'].astype(str).str.replace("1","maize")
df2['maize'] = df2['maize'].astype(str).str.replace("0","")
df2['chari'] = df2['chari'].astype(str).str.replace("1","chari")
df2['chari'] = df2['chari'].astype(str).str.replace("0","")
df2['jawar'] = df2['jawar'].astype(str).str.replace("1","jawar")
df2['jawar'] = df2['jawar'].astype(str).str.replace("0","")

df2['Wheat Straw'] = df2['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df2['Wheat Straw'] = df2['Wheat Straw'].astype(str).str.replace("0","")
df2['Paddy Straw'] = df2['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df2['Paddy Straw'] = df2['Paddy Straw'].astype(str).str.replace("0","")

df3=pd.read_excel('Initial Data\SM Gurdaspur_Revised.xlsx',index_col=0,sheet_name=2, usecols="A:H,O:Q,X:AG",skiprows=1)
df3.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df3['Barseem'] = df3['Barseem'].astype(str).str.replace("1","Barseem")
df3['Barseem'] = df3['Barseem'].astype(str).str.replace("0","")
df3['Bajra'] = df3['Bajra'].astype(str).str.replace("1","Bajra")
df3['Bajra'] = df3['Bajra'].astype(str).str.replace("0","")
df3['maize'] = df3['maize'].astype(str).str.replace("1","maize")
df3['maize'] = df3['maize'].astype(str).str.replace("0","")
df3['chari'] = df3['chari'].astype(str).str.replace("1","chari")
df3['chari'] = df3['chari'].astype(str).str.replace("0","")
df3['jawar'] = df3['jawar'].astype(str).str.replace("1","jawar")
df3['jawar'] = df3['jawar'].astype(str).str.replace("0","")

df3['Wheat Straw'] = df3['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df3['Wheat Straw'] = df3['Wheat Straw'].astype(str).str.replace("0","")
df3['Paddy Straw'] = df3['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df3['Paddy Straw'] = df3['Paddy Straw'].astype(str).str.replace("0","")

df4=pd.read_excel('Initial Data\SM Hoshiarpur_Revised.xlsx',index_col=0,sheet_name=2, usecols="A:H,O:Q,X:AG",skiprows=1)
df4.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df4['Barseem'] = df4['Barseem'].astype(str).str.replace("1","Barseem")
df4['Barseem'] = df4['Barseem'].astype(str).str.replace("0","")
df4['Bajra'] = df4['Bajra'].astype(str).str.replace("1","Bajra")
df4['Bajra'] = df4['Bajra'].astype(str).str.replace("0","")
df4['maize'] = df4['maize'].astype(str).str.replace("1","maize")
df4['maize'] = df4['maize'].astype(str).str.replace("0","")
df4['chari'] = df4['chari'].astype(str).str.replace("1","chari")
df4['chari'] = df4['chari'].astype(str).str.replace("0","")
df4['jawar'] = df4['jawar'].astype(str).str.replace("1","jawar")
df4['jawar'] = df4['jawar'].astype(str).str.replace("0","")

df4['Wheat Straw'] = df4['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df4['Wheat Straw'] = df4['Wheat Straw'].astype(str).str.replace("0","")
df4['Paddy Straw'] = df4['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df4['Paddy Straw'] = df4['Paddy Straw'].astype(str).str.replace("0","")

df5=pd.read_excel('Initial Data\SW Muktsar_Revised.xlsx',index_col=0,sheet_name=2, usecols="A:H,O:Q,X:AG",skiprows=1)
df5.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df5['Barseem'] = df5['Barseem'].astype(str).str.replace("1","Barseem")
df5['Barseem'] = df5['Barseem'].astype(str).str.replace("0","")
df5['Bajra'] = df5['Bajra'].astype(str).str.replace("1","Bajra")
df5['Bajra'] = df5['Bajra'].astype(str).str.replace("0","")
df5['maize'] = df5['maize'].astype(str).str.replace("1","maize")
df5['maize'] = df5['maize'].astype(str).str.replace("0","")
df5['chari'] = df5['chari'].astype(str).str.replace("1","chari")
df5['chari'] = df5['chari'].astype(str).str.replace("0","")
df5['jawar'] = df5['jawar'].astype(str).str.replace("1","jawar")
df5['jawar'] = df5['jawar'].astype(str).str.replace("0","")

df5['Wheat Straw'] = df5['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df5['Wheat Straw'] = df5['Wheat Straw'].astype(str).str.replace("0","")
df5['Paddy Straw'] = df5['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df5['Paddy Straw'] = df5['Paddy Straw'].astype(str).str.replace("0","")

df6=pd.read_excel('Concentrate Feed Modelling\Central Ludhiana.xlsx',index_col=0,sheet_name=3, usecols="A:H,O:Q,X:AG",skiprows=1)
df6.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df6['Barseem'] = df6['Barseem'].astype(str).str.replace("1","Barseem")
df6['Barseem'] = df6['Barseem'].astype(str).str.replace("0","")
df6['Bajra'] = df6['Bajra'].astype(str).str.replace("1","Bajra")
df6['Bajra'] = df6['Bajra'].astype(str).str.replace("0","")
df6['maize'] = df6['maize'].astype(str).str.replace("1","maize")
df6['maize'] = df6['maize'].astype(str).str.replace("0","")
df6['chari'] = df6['chari'].astype(str).str.replace("1","chari")
df6['chari'] = df6['chari'].astype(str).str.replace("0","")
df6['jawar'] = df6['jawar'].astype(str).str.replace("1","jawar")
df6['jawar'] = df6['jawar'].astype(str).str.replace("0","")

df6['Wheat Straw'] = df6['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df6['Wheat Straw'] = df6['Wheat Straw'].astype(str).str.replace("0","")
df6['Paddy Straw'] = df6['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df6['Paddy Straw'] = df6['Paddy Straw'].astype(str).str.replace("0","")

df7=pd.read_excel('Concentrate Feed Modelling\Central Sangrur.xlsx',index_col=0,sheet_name=3, usecols="A:H,O:Q,X:AG",skiprows=1)
df7.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df7['Barseem'] = df7['Barseem'].astype(str).str.replace("1","Barseem")
df7['Barseem'] = df7['Barseem'].astype(str).str.replace("0","")
df7['Bajra'] = df7['Bajra'].astype(str).str.replace("1","Bajra")
df7['Bajra'] = df7['Bajra'].astype(str).str.replace("0","")
df7['maize'] = df7['maize'].astype(str).str.replace("1","maize")
df7['maize'] = df7['maize'].astype(str).str.replace("0","")
df7['chari'] = df7['chari'].astype(str).str.replace("1","chari")
df7['chari'] = df7['chari'].astype(str).str.replace("0","")
df7['jawar'] = df7['jawar'].astype(str).str.replace("1","jawar")
df7['jawar'] = df7['jawar'].astype(str).str.replace("0","")

df7['Wheat Straw'] = df7['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df7['Wheat Straw'] = df7['Wheat Straw'].astype(str).str.replace("0","")
df7['Paddy Straw'] = df7['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df7['Paddy Straw'] = df7['Paddy Straw'].astype(str).str.replace("0","")

df8=pd.read_excel('Concentrate Feed Modelling\SM Gurdaspur.xlsx',index_col=0,sheet_name=3, usecols="A:H,O:Q,X:AG",skiprows=1)
df8.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df8['Barseem'] = df8['Barseem'].astype(str).str.replace("1","Barseem")
df8['Barseem'] = df8['Barseem'].astype(str).str.replace("0","")
df8['Bajra'] = df8['Bajra'].astype(str).str.replace("1","Bajra")
df8['Bajra'] = df8['Bajra'].astype(str).str.replace("0","")
df8['maize'] = df8['maize'].astype(str).str.replace("1","maize")
df8['maize'] = df8['maize'].astype(str).str.replace("0","")
df8['chari'] = df8['chari'].astype(str).str.replace("1","chari")
df8['chari'] = df8['chari'].astype(str).str.replace("0","")
df8['jawar'] = df8['jawar'].astype(str).str.replace("1","jawar")
df8['jawar'] = df8['jawar'].astype(str).str.replace("0","")

df8['Wheat Straw'] = df8['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df8['Wheat Straw'] = df8['Wheat Straw'].astype(str).str.replace("0","")
df8['Paddy Straw'] = df8['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df8['Paddy Straw'] = df8['Paddy Straw'].astype(str).str.replace("0","")


df9=pd.read_excel('Concentrate Feed Modelling\SM Hoshiarpur.xlsx',index_col=0,sheet_name=3, usecols="A:H,O:Q,X:AG",skiprows=1)
df9.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df9['Barseem'] = df9['Barseem'].astype(str).str.replace("1","Barseem")
df9['Barseem'] = df9['Barseem'].astype(str).str.replace("0","")
df9['Bajra'] = df9['Bajra'].astype(str).str.replace("1","Bajra")
df9['Bajra'] = df9['Bajra'].astype(str).str.replace("0","")
df9['maize'] = df9['maize'].astype(str).str.replace("1","maize")
df9['maize'] = df9['maize'].astype(str).str.replace("0","")
df9['chari'] = df9['chari'].astype(str).str.replace("1","chari")
df9['chari'] = df9['chari'].astype(str).str.replace("0","")
df9['jawar'] = df9['jawar'].astype(str).str.replace("1","jawar")
df9['jawar'] = df9['jawar'].astype(str).str.replace("0","")

df9['Wheat Straw'] = df9['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df9['Wheat Straw'] = df9['Wheat Straw'].astype(str).str.replace("0","")
df9['Paddy Straw'] = df9['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df9['Paddy Straw'] = df9['Paddy Straw'].astype(str).str.replace("0","")

df10=pd.read_excel('Concentrate Feed Modelling\SW Muktsar.xlsx',index_col=0,sheet_name=3, usecols="A:H,O:Q,X:AG",skiprows=1)
df10.rename(columns = {'Unnamed: 1':'Month','Buffalo/Cow':'GF given to in milk','Buffalo/Cow.1':'DF given to in milk','Unnamed: 23':'Milk produced by farm/day', 'Unnamed: 24':'Max T', 'Unnamed: 25':'Min T', 'Unnamed: 26':'Mean T', 'Unnamed: 27':'RH', 'Unnamed: 28':'Rainfall', 'Unnamed: 29':'THI', 'Unnamed: 30':'farm size'},inplace=True)
df10['Barseem'] = df10['Barseem'].astype(str).str.replace("1","Barseem")
df10['Barseem'] = df10['Barseem'].astype(str).str.replace("0","")
df10['Bajra'] = df10['Bajra'].astype(str).str.replace("1","Bajra")
df10['Bajra'] = df10['Bajra'].astype(str).str.replace("0","")
df10['maize'] = df10['maize'].astype(str).str.replace("1","maize")
df10['maize'] = df10['maize'].astype(str).str.replace("0","")
df10['chari'] = df10['chari'].astype(str).str.replace("1","chari")
df10['chari'] = df10['chari'].astype(str).str.replace("0","")
df10['jawar'] = df10['jawar'].astype(str).str.replace("1","jawar")
df10['jawar'] = df10['jawar'].astype(str).str.replace("0","")

df10['Wheat Straw'] = df10['Wheat Straw'].astype(str).str.replace("1","Wheat Straw")
df10['Wheat Straw'] = df10['Wheat Straw'].astype(str).str.replace("0","")
df10['Paddy Straw'] = df10['Paddy Straw'].astype(str).str.replace("1","Paddy Straw")
df10['Paddy Straw'] = df10['Paddy Straw'].astype(str).str.replace("0","")

frames = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10]
result = pd.concat(frames)

result["Green Fodder"] = result['Barseem'].astype(str) +result['Bajra'].astype(str)+ result['maize'].astype(str)+result['chari'].astype(str)+result['jawar'].astype(str)
result=result.drop(['Barseem'], axis=1)
result=result.drop(['Bajra'], axis=1)
result=result.drop(['maize'], axis=1)
result=result.drop(['chari'], axis=1)
result=result.drop(['jawar'], axis=1)

result["Dry Fodder"] = result['Wheat Straw'].astype(str) +result['Paddy Straw'].astype(str)
result=result.drop(['Wheat Straw'], axis=1)
result=result.drop(['Paddy Straw'], axis=1)

result["Farm Milk Production/Day"]=result['Milk produced by farm/day'].astype(str)
result=result.drop(['Milk produced by farm/day'], axis=1)

result.fillna(method='ffill', inplace=True)
  
result['GF given to in milk'] = result['GF given to in milk'].astype(str).str.replace("^0$","30",regex=True)
result['DF given to in milk'] = result['DF given to in milk'].astype(str).str.replace("^0.0$","3.0",regex=True)

result=result.fillna(method="ffill")

excelpath = 'Concentrate Feed Modelling with FS\Extrinsic Combined data.xlsx'
with pd.ExcelWriter(excelpath) as writer:
#     (result.loc[result['Green Fodder']!=''&result['Dry Fodder']!='']).to_excel(writer, sheet_name = 'Sheet1')
    result.to_excel(writer,sheet_name='Sheet1')